version: '3.8'
services:
  react-app:
    container_name: react-app
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
    env_file: ./.env
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}